import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@/app/globals.css"
import Modal from "@/components/modal"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
                {children}
                <footer className="bg-white h-20 flex items-center justify-center text-center text-gray-800 text-sm font-semibold">
                    <p>Designer: Kevin || Developer: Victren</p>
                </footer>
                <Modal initialIsOpen={false} />
            </body>
        </html>
    )
}
